require:
  - rubocop-performance
  - rubocop-rspec

inherit_gem:
  rentacop:
    - rentacop.yml
    - rspec.yml

inherit_mode:
  merge:
    - Exclude
    - Include

AllCops:
  TargetRubyVersion: 3.0
  Exclude:
    - 'port/**/*'

Style/NumericLiterals:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'bin/concode'

