language: ruby

rvm:
  - "2.3.0"
  - "2.5.3"
  - "2.6.3"

before_install:
# - source ~/virtualenv/python3.6/bin/activate
# - pip3 install codenamize
- gem install bundler
- pip install --user codenamize

script:
- bundle exec rspec
