language: ruby

rvm:
- "2.3"
- "2.4"
- "2.5"
- "2.6"
- "2.7"

before_install:
# - source ~/virtualenv/python3.6/bin/activate
# - pip3 install codenamize
- gem install bundler
- pip install --user codenamize

script:
- bundle exec rspec
