name: Test
on:
  pull_request:
  push: { branches: master }

jobs:
  test:
    name: Ruby ${{ matrix.ruby }}

    runs-on: ubuntu-latest

    strategy:
      matrix: { ruby: ['2.4', '2.5', '2.6', '2.7'] }

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Cache gem dependencies
      uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-${{ matrix.ruby }}-bundle

    - name: Setup Ruby
      uses: actions/setup-ruby@v1
      with: { ruby-version: '${{ matrix.ruby }}' }

    - name: Bundle install
      run: |
        gem install bundler
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3

    - name: Setup Python
      uses: actions/setup-python@v1
      with: { python-version: '3.6' }

    - name: Install python codenamize
      run: |
        pip3 install codenamize
        codenamize --version

    - name: Run tests
      run: bundle exec rspec
