name: Test
on:
  pull_request:
  push: { branches: master }

jobs:
  test:
    name: Ruby ${{ matrix.ruby }}

    runs-on: ubuntu-latest

    strategy:
      matrix: { ruby: ['2.7', '3.0', '3.1', '3.2', head] }

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install OS dependencies
      run: sudo apt-get -y install libyaml-dev

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '${{ matrix.ruby }}'
        bundler-cache: true

    - name: Setup Python
      uses: actions/setup-python@v4
      with: { python-version: '3.10' }

    - name: Install python codenamize
      run: |
        pip3 install codenamize
        codenamize --version

    - name: Run tests
      run: bundle exec rspec
